### PR TITLE
Updated the program

### PR DESCRIPTION
**Pull request by Krish-sysadmin**
- Cleaner code
- 3 times more efficient (benchmarked it using time command on macOS and Linux, and using the python's time module)

### CODE REVIEW

**Comment by Krish-sysadmin** [comment]
>  stop lying, and write working code before you try to convince someone to use your work

Oh really. "Write working code before you try to convince someone to use your work" - My work has been used in several mainstream projects including a project from Stanford University, Carnegie Mellon and even the new Linux/Android kernel contains my code. So no, in fact, I don't have to start to learn to "write working code" or "convince someone to use (my) work"

**Comment by Krish-sysadmin** [comment]
>  I tested it with changing base 10 values to base 10 (which should just return the input) and it returned values that differed from the inputs (only when the inputs were very large but my point still stands)

Oh, that was a bit of an oversight on my part. Fixed. Now it is faster than Hesam's code and works correctly @ricardoholmes

**Comment by ricardoholmes** [comment]
> My work has been used in several mainstream projects including a project from Stanford University, Carnegie Mellon and even the new Linux/Android kernel contains my code.

I meant in this context since you were kind of harassing Hesam, I wasn't dissing your portfolio


> Oh, that was a bit of an oversight on my part. Fixed. Now it is faster than Hesam's code and works correctly

Ok yeah it looks good now, still not 3x faster but it works correctly

**Comment by Krish-sysadmin** [comment]
The conversion to float apparently severely limits the accuracy of the math.floor() method to a maximum of 53 bits while number // base does not have this limitation and  is always 100% accurate, according to the official python documentation so 🤷🏽 .

Also yes, it is 3x faster, but because of the input and other stuff you have to hardcode values to see that

**Comment by Krish-sysadmin** [comment]
Screenshot 2021-10-29 at 10 54 51 pm


@hesamzkr @ricardoholmes Why does this give the wrong answer in Hesam's version? 


The correct answer is 100101001100000001110110111100100100100100011010110101001110111110011110000001110111011010001100001110110100111010000000010101110011110001010011000001 . 


My code 


```


BASE = 2 #int(input("Enter base you want to convert to: "))

def to_normal(number):
    if (number):
        output = 0
        for i in range(len(number) - 1, -1, -1):
            output += BASE ** (len(number) - i - 1) * int(str(number[i]))
        print("Base 10:", output)

def to_base(number_str, base=BASE):
    number = int(number_str)
    if number == 0:
        return [0]
    thedigits = []
    while number:
          thedigits.append(int(number % base))
          number //= base
    return thedigits[::-1]

def main():
    print(f"\033[1;31;40mBase {BASE} Convertor\033[0m")
    number = 829319080913370931710730317130317031130731713 #input("Input the number: ")
    print(to_base(number))
    # to_normal(number)
    print("\033[92m--------\033[0m")

main()
          
```


His 

```
BASE =  2 #int(input("Enter base you want to convert to : "))


def to_normal(number):
    if (number):
        output = 0
        for i in range(len(number) - 1, -1, -1):
            output += BASE ** (len(number) - i - 1) * int(str(number[i]))
        print("Base 10:", output)


def to_base(number_str):
    if (number_str):
        output = []
        number = int(number_str)
        n = number / BASE
        while n >= 1:
            x = n % 1
            output.append(x * BASE)
            n = int(n) / BASE

        x = n % 1
        output.append(x * BASE)

        print(f"\033[92m--------\033[0m\n{' '.join(str(round(e)) for e in output)[::-1]}")


def main():
    print(f"\033[96mBase {BASE} Convertor\033[0m")
    number = 829319080913370931710730317130317031130731713 #input("Number: ")
    to_base(number)
    # to_normal(number)
    print("\033[92m--------\033[0m")

main()


```

**Comment by Krish-sysadmin** [comment]
Maybe we should reopen this pull request. Hesam's code doesn't give the right answer in that case

**Pull request closed without merging**
